### ISSUE TITLE
E-step calculation for the extruder does not seem to be correct.

### ISSUE THREAD

**Issue by JonVogel** [iFrostizz/OctoPrint-CalibrationCompanion#30]
My e-step is the default value of 93.  I extrude 100mm of filament and get a piece that's 97mm long.  Doing the math, my new e-step value should be 95.7.  But, the e-step calculator says that the e-step should be 404.35?  This can't be correct.  Please check the math on this.

**Comment by iFrostizz** [comment]
Hey!

It look like you didn't entered the correct values.
As explained in the video shared in the readme of the plugin https://github.com/iFrostizz/OctoPrint-CalibrationCompanion#e-steps , a mark should be made as `DistanceToExtrude + 20mm`.  Then extrude the value of `DistanceToExtrude` to have a 20mm gap taking in account accuracies because of an not calibrated esteps value, and measure the distance left.
So if the piece that you're getting is 97mm long, the distance left between the extruder enter and the mark done before should be 23mm.
![image](https://user-images.githubusercontent.com/51274081/134787268-b815e973-f24d-4f88-86a4-2858ab8d2fb5.png)
That's pretty much what you've calculated !
Maybe that the e-steps calculation is not too intuitive, please let me know.

**Comment by JonVogel** [comment]
Hi!  I just installed the plug-in and tried to use it.  I didn’t know there was a video. What I do usually with e-step calibration is remove the Bowden connector, cut the filament off at the extruder, extrude 10cm and measure it.   That’s used to calculate the e-steps.   Your 20mm this and that is confusing.  

Regards,

Jon

**Comment by iFrostizz** [comment]
Just added a little text pointing to the README in the plugin introduction https://github.com/iFrostizz/OctoPrint-CalibrationCompanion/commit/446d57889cb1ab933e93a89ab6d045b85d2f1378
